prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","lib")   )
setenv( "LMOD_ZLIB_DIR",     "/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23"                     )
setenv( "LMOD_ZLIB_INC",     pathJoin("/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","include")   )
setenv( "LMOD_ZLIB_LIB",     pathJoin("/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","lib")   )
setenv( "TACC_ZLIB_DIR",     "/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23"                     )
setenv( "TACC_ZLIB_INC",     pathJoin("/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","include")   )
setenv( "TACC_ZLIB_LIB",     pathJoin("/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","lib")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23","share/pkgconfig" ) )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/zlib/installation-1.2.13-milan-intel23" )
