prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23","lib")   )
setenv( "LMOD_BOOST_DIR",     "/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23"                     )
setenv( "LMOD_BOOST_INC",     pathJoin("/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23","include")   )
setenv( "LMOD_BOOST_LIB",     pathJoin("/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23","lib")   )
setenv( "TACC_BOOST_DIR",     "/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23"                     )
setenv( "TACC_BOOST_INC",     pathJoin("/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23","include")   )
setenv( "TACC_BOOST_LIB",     pathJoin("/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/boost/installation-1.81.0-milan-intel23" )
