prepend_path( "PATH",           pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","bin")   )
setenv( "LMOD_SWIG_BIN",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","bin")   )
setenv( "TACC_SWIG_BIN",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","lib")   )
setenv( "LMOD_SWIG_DIR",     "/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23"                     )
setenv( "LMOD_SWIG_INC",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","include")   )
setenv( "LMOD_SWIG_LIB",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","lib")   )
setenv( "TACC_SWIG_DIR",     "/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23"                     )
setenv( "TACC_SWIG_INC",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","include")   )
setenv( "TACC_SWIG_LIB",     pathJoin("/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work/00434/eijkhout/swig/installation-4.1.1-milan-intel23" )
